# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\saans\AppData\Local\Programs\Python\Python310\Lib\site-packages\qt5_applications\Qt\bin\Trial2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ProjectDetails_BridgeANDTrafficData_Window import Ui_BridgeTraffic_Dialog
from ProjectDetails_Foundation_Window import Ui_Foundation_Dialog
from ProjectDetails_CarbonEmissionData_Window import Ui_CarbonEmission_Dialog
from ProjectDetails_DemolitionANDRecyclingData_Window import Ui_Demolition_Dialog
from ProjectDetails_FinancialData_Window import Ui_FinancialData_Dialog
from ProjectDetails_MaintenanceANDRepairData_Window import Ui_Maintenance_Dialog
from ProjectDetails_Miscellaneous_Window import Ui_Miscellaneous_Dialog
from ProjectDetails_SubStructure_Window import Ui_SubStructure_Dialog
from ProjectDetails_SuperStructure_Window import Ui_SuperStructure_Dialog

class Ui_MainWindow(object):
    def openBridgeTrafficWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_BridgeTraffic_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openFoundationWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Foundation_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openCarbonEmissionWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_CarbonEmission_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openDemolitionWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Demolition_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()
    
    def openFinancialWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_FinancialData_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openMaintenanceWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Maintenance_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openMiscellaneousWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_Miscellaneous_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSubStructureWindow(self):   
        self.window = QtWidgets.QDialog()
        self.ui = Ui_SubStructure_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    def openSuperStructureWindow(self):
        self.window = QtWidgets.QDialog()
        self.ui = Ui_SuperStructure_Dialog()
        self.ui.setupUi(self.window)
        self.window.show()

    # ...existing code...

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 1024)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Create a main vertical layout for the central widget
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)  # Remove margins
        self.mainLayout.setSpacing(2)  # Minimal spacing between elements

        # Create a horizontal layout for the buttons
        self.topButtonLayout = QtWidgets.QHBoxLayout()
        self.topButtonLayout.setSpacing(2)  # Minimal spacing between buttons

        # Add "General Information" button
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setText("General Information")
        self.pushButton.setCheckable(True)
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 230)")
        self.topButtonLayout.addWidget(self.pushButton)

        # Add "Input Parameters" button
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setText("Input Parameters")
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 230)")
        self.topButtonLayout.addWidget(self.pushButton_2)

        # Add "Outputs" button
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setText("Outputs")
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setStyleSheet("background-color: rgb(240, 230, 230)")
        self.topButtonLayout.addWidget(self.pushButton_10)

        # Add the button layout to the main layout
        self.mainLayout.addLayout(self.topButtonLayout)

        # Tab widget setup
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "Tutorials")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "Project Details")

        # Add the tab widget to the main layout
        self.mainLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(220, 0, 771, 971))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea.setGeometry(QtCore.QRect(0, 10, 771, 941))
        self.scrollArea.setStyleSheet("background-color: #fff9f9")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 769, 939))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.Menu_Widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.Menu_Widget.setGeometry(QtCore.QRect(10, 0, 731, 931))
        self.Menu_Widget.setObjectName("Menu_Widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Menu_Widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(self.Menu_Widget)
        self.widget.setMinimumSize(QtCore.QSize(641, 0))
        self.widget.setMaximumSize(QtCore.QSize(641, 42))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("background-color: rgb(240,230,230)")
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(9, 9, 144, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("background-color: rgb(240, 230, 230)")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/play_arrow_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/play_arrow_filled (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.Menu_Widget)
        self.widget_2.setMinimumSize(QtCore.QSize(641, 391))
        self.widget_2.setStyleSheet("background-color: #fff9f9")
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit.setGeometry(QtCore.QRect(160, 20, 401, 20))
        self.lineEdit.setStyleSheet("background-color: #ffffff")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(160, 60, 401, 20))
        self.lineEdit_2.setStyleSheet("background-color: #ffffff")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(160, 100, 401, 71))
        self.textEdit.setStyleSheet("background-color: #ffffff")
        self.textEdit.setObjectName("textEdit")
        self.widget1 = QtWidgets.QWidget(self.widget_2)
        self.widget1.setGeometry(QtCore.QRect(160, 190, 194, 181))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_3.setStyleSheet("background-color: #ffffff")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_4.setStyleSheet("background-color: #ffffff")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_5.setStyleSheet("background-color: #ffffff")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.comboBox = QtWidgets.QComboBox(self.widget1)
        self.comboBox.setStyleSheet("background-color: #ffffff")
        self.comboBox.setObjectName("comboBox")
        for k in range(244):
            self.comboBox.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_6.setStyleSheet("background-color: #ffffff")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_2.addWidget(self.lineEdit_6)
        self.widget2 = QtWidgets.QWidget(self.widget_2)
        self.widget2.setGeometry(QtCore.QRect(10, 190, 131, 181))
        self.widget2.setObjectName("widget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.verticalLayout_3.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.Menu_Widget)
        self.widget_3.setMaximumSize(QtCore.QSize(641, 41))
        self.widget_3.setStyleSheet("background-color: rgb(240,230,230)")
        self.widget_3.setObjectName("widget_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(9, 9, 128, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(240, 230, 230)")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_5 = QtWidgets.QWidget(self.Menu_Widget)
        self.widget_5.setEnabled(True)
        self.widget_5.setMinimumSize(QtCore.QSize(641, 191))
        self.widget_5.setMaximumSize(QtCore.QSize(641, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.widget_5.setFont(font)
        self.widget_5.setStyleSheet("background-color: rgb(240, 230, 230)")
        self.widget_5.setObjectName("widget_5")
        self._2 = QtWidgets.QGridLayout(self.widget_5)
        self._2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self._2.setContentsMargins(0, -1, 0, -1)
        self._2.setObjectName("_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setCheckable(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self._2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.widget_5)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_4, clicked=lambda: self.openFoundationWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/play_arrow_filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_4, clicked=lambda: self.openSuperStructureWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_4, clicked=lambda: self.openSubStructureWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setIcon(icon1)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 2, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_4, clicked=lambda: self.openMiscellaneousWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 3, 0, 1, 1)
        self._2.addWidget(self.widget_4, 1, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_5, clicked=lambda: self.openFinancialWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self._2.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setCheckable(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self._2.addWidget(self.pushButton_5, 3, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.widget_5)
        self.widget_8.setMaximumSize(QtCore.QSize(281, 21))
        self.widget_8.setObjectName("widget_8")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_8, clicked=lambda: self.openCarbonEmissionWindow())
        self.pushButton_14.setGeometry(QtCore.QRect(90, 0, 183, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setObjectName("pushButton_14")
        self._2.addWidget(self.widget_8, 4, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_5, clicked=lambda: self.openBridgeTrafficWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self._2.addWidget(self.pushButton_7, 5, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_5, clicked=lambda: self.openMaintenanceWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self._2.addWidget(self.pushButton_8, 6, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_5, clicked=lambda: self.openDemolitionWindow())
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self._2.addWidget(self.pushButton_9, 7, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.widget_6 = QtWidgets.QWidget(self.Menu_Widget)
        self.widget_6.setMaximumSize(QtCore.QSize(641, 41))
        self.widget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_6.setStyleSheet("background-color: rgb(240,230,230)")
        self.widget_6.setObjectName("widget_6")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_6)
        self.pushButton_10.setGeometry(QtCore.QRect(9, 9, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_10.setStyleSheet("background-color: rgb(240, 230, 230)")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_3.addWidget(self.widget_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 0, 64, 22))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Vector.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon2)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Vector (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon3)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/🦆 icon _save action floppy_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon4)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/🦆 icon _document save as template_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave_As.setIcon(icon5)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionCreate_a_Copy = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/🦆 icon _file copy_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreate_a_Copy.setIcon(icon6)
        self.actionCreate_a_Copy.setObjectName("actionCreate_a_Copy")
        self.actionPrint = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Vector (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrint.setIcon(icon7)
        self.actionPrint.setObjectName("actionPrint")
        self.actionRename = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Vector (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRename.setIcon(icon8)
        self.actionRename.setObjectName("actionRename")
        self.actionExport = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExport.setIcon(icon9)
        self.actionExport.setObjectName("actionExport")
        self.actionVersion_History = QtWidgets.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Vector (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVersion_History.setIcon(icon10)
        self.actionVersion_History.setObjectName("actionVersion_History")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Alert Circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionInfo.setIcon(icon11)
        self.actionInfo.setObjectName("actionInfo")
        self.actionContact_Us = QtWidgets.QAction(MainWindow)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Contact.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionContact_Us.setIcon(icon12)
        self.actionContact_Us.setObjectName("actionContact_Us")
        self.actionFeedback = QtWidgets.QAction(MainWindow)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/🦆 icon _Person Feedback_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFeedback.setIcon(icon13)
        self.actionFeedback.setObjectName("actionFeedback")
        self.actionVideo_Tutorials = QtWidgets.QAction(MainWindow)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/🦆 icon _youtube_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVideo_Tutorials.setIcon(icon14)
        self.actionVideo_Tutorials.setObjectName("actionVideo_Tutorials")
        self.actionJoin_our_Community = QtWidgets.QAction(MainWindow)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/🦆 icon _People Community_.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJoin_our_Community.setIcon(icon15)
        self.actionJoin_our_Community.setObjectName("actionJoin_our_Community")
        self.actionEdit = QtWidgets.QAction(MainWindow)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/08b7798a84ffe0528bdec7dc8efe8fb1c89f77ae.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEdit.setIcon(icon16)
        self.actionEdit.setObjectName("actionEdit")
        self.actionFile = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/Icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFile.setIcon(icon17)
        self.actionFile.setObjectName("actionFile")
        self.actionOpen_File = QtWidgets.QAction(MainWindow)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("C:\\Users\\saans\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\qt5_applications\\Qt\\bin\\../../../../../../../../../../Downloads/78ff94ca74c504343b797700f5d515a40ab72143.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen_File.setIcon(icon18)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionCreate_a_Copy)
        self.menuFile.addAction(self.actionPrint)
        self.menuFile.addAction(self.actionRename)
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addAction(self.actionVersion_History)
        self.menuFile.addAction(self.actionInfo)
        self.menuHelp.addAction(self.actionContact_Us)
        self.menuHelp.addAction(self.actionFeedback)
        self.menuHelp.addAction(self.actionVideo_Tutorials)
        self.menuHelp.addAction(self.actionJoin_our_Community)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHome.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionEdit)
        self.toolBar.addAction(self.actionFile)
        self.toolBar.addAction(self.actionOpen_File)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.pushButton.toggled['bool'].connect(self.widget_2.setVisible) # type: ignore
        self.pushButton_2.toggled['bool'].connect(self.widget_5.setVisible) # type: ignore
        self.pushButton_4.toggled['bool'].connect(self.widget_4.setVisible) # type: ignore
        self.pushButton_5.toggled['bool'].connect(self.widget_8.setVisible) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Initially hide details
        self.widget_2.setVisible(False)  # General Information details
        self.widget_5.setVisible(False)  # Input Parameters details
        self.widget_8.setVisible(False)  # Carbon Emission subdetails (already handled)
        self.widget_4.setVisible(False)  # Structure subdetails (already handled)
        
        # Setup expand/collapse
        self.pushButton.toggled['bool'].connect(self.widget_2.setVisible)
        self.pushButton_2.toggled['bool'].connect(self.widget_5.setVisible)
        self.pushButton_10.toggled['bool'].connect(self.show_outputs_section)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tutorials"))
        self.pushButton.setText(_translate("MainWindow", "General Information"))
        self.label_2.setText(_translate("MainWindow", "Comapany Name"))
        self.label_3.setText(_translate("MainWindow", "Project Title"))
        self.label_4.setText(_translate("MainWindow", "Project Description"))
        dic_of_countries = {
            "Afghanistan": "AF",
            "Albania": "AL",
            "Algeria": "DZ",
            "American Samoa": "AS",
            "Andorra": "AD",
            "Angola": "AO",
            "Anguilla": "AI",
            "Antarctica": "AQ",
            "Antigua and Barbuda": "AG",
            "Argentina": "AR",
            "Armenia": "AM",
            "Aruba": "AW",
            "Australia": "AU",
            "Austria": "AT",
            "Azerbaijan": "AZ",
            "Bahamas": "BS",
            "Bahrain": "BH",
            "Bangladesh": "BD",
            "Barbados": "BB",
            "Belarus": "BY",
            "Belgium": "BE",
            "Belize": "BZ",
            "Benin": "BJ",
            "Bermuda": "BM",
            "Bhutan": "BT",
            "Bolivia": "BO",
            "Bosnia and Herzegovina": "BA",
            "Botswana": "BW",
            "Brazil": "BR",
            "British Indian Ocean Territory": "IO",
            "Brunei Darussalam": "BN",
            "Bulgaria": "BG",
            "Burkina Faso": "BF",
            "Burundi": "BI",
            "Cambodia": "KH",
            "Cameroon": "CM",
            "Canada": "CA",
            "Cape Verde": "CV",
            "Central African Republic": "CF",
            "Cayman Islands": "KY",
            "Chad": "TD",
            "Chile": "CL",
            "China": "CN",
            "Christmas Island": "CX",
            "Cocos (Keeling) Islands": "CC",
            "Colombia": "CO",
            "Comoros": "KM",
            "Congo": "CG",
            "Cook Islands": "CK",
            "Costa Rica": "CR",
            "Croatia": "HR",
            "Cuba": "CU",
            "Cyprus": "CY",
            "Czech Republic": "CZ",
            "Denmark": "DK",
            "Djibouti": "DJ",
            "Dominica": "DM",
            "Dominican Republic": "DO",
            "Ecuador": "EC",
            "Egypt": "EG",
            "El Salvador": "SV",
            "Equatorial Guinea": "GQ",
            "Eritrea": "ER",
            "Estonia": "EE",
            "Eswatini": "SZ",
            "Ethiopia": "ET",
            "Falkland Islands (Malvinas)": "FK",
            "Faroe Islands": "FO",
            "Fiji": "FJ",
            "Finland": "FI",
            "France": "FR",
            "French Guiana": "GF",
            "French Polynesia": "PF",
            "French Southern Territories": "TF",
            "Gabon": "GA",
            "Gambia": "GM",
            "Georgia": "GE",
            "Germany": "DE",
            "Ghana": "GH",
            "Gibraltar": "GI",
            "Greece": "GR",
            "Greenland": "GL",  
            "Grenada": "GD",
            "Guadeloupe": "GP",
            "Guam": "GU",
            "Guatemala": "GT",
            "Guernsey": "GG",
            "Guinea": "GN",
            "Guinea-Bissau": "GW",
            "Guyana": "GY",
            "Haiti": "HT",
            "Heard Island and McDonald Islands": "HM",
            "Holy See (Vatican City State)": "VA",
            "Honduras": "HN",
            "Hong Kong": "HK",
            "Hungary": "HU",
            "Iceland": "IS",    
            "India": "IN",
            "Indonesia": "ID",
            "Iran (Islamic Republic of)": "IR",
            "Iraq": "IQ",
            "Ireland": "IE",
            "Isle of Man": "IM",
            "Israel": "IL",
            "Italy": "IT",
            "Jamaica": "JM",
            "Japan": "JP",
            "Jersey": "JE",
            "Jordan": "JO",
            "Kazakhstan": "KZ",
            "Kenya": "KE",
            "Kiribati": "KI",
            "Korea (Democratic People's Republic of)": "KP",
            "Korea, Republic of": "KR",
            "Kuwait": "KW",
            "Kyrgyzstan": "KG",
            "Lao People's Democratic Republic": "LA",
            "Latvia": "LV",
            "Lebanon": "LB",
            "Lesotho": "LS",
            "Liberia": "LR",
            "Libya": "LY",
            "Liechtenstein": "LI",
            "Lithuania": "LT",
            "Luxembourg": "LU",
            "Macao": "MO",
            "Macedonia (the former Yugoslav Republic of)": "MK",
            "Madagascar": "MG",
            "Malawi": "MW",
            "Malaysia": "MY",
            "Maldives": "MV",
            "Mali": "ML",
            "Malta": "MT",
            "Marshall Islands": "MH",
            "Martinique": "MQ",
            "Mauritania": "MR",
            "Mauritius": "MU",
            "Mayotte": "YT",
            "Mexico": "MX",
            "Micronesia (Federated States of)": "FM",
            "Moldova (Republic of)": "MD",
            "Monaco": "MC",
            "Mongolia": "MN",
            "Montenegro": "ME",
            "Montserrat": "MS",
            "Morocco": "MA",
            "Mozambique": "MZ",
            "Myanmar": "MM",
            "Namibia": "NA",
            "Nauru": "NR",
            "Nepal": "NP",
            "Netherlands": "NL",
            "New Caledonia": "NC",
            "New Zealand": "NZ",
            "Nicaragua": "NI",
            "Niger": "NE",
            "Nigeria": "NG",
            "Niue": "NU",
            "Norfolk Island": "NF",
            "North Macedonia": "MK",
            "Northern Mariana Islands": "MP",
            "Norway": "NO",
            "Oman": "OM",
            "Pakistan": "PK",
            "Palau": "PW",
            "Palestine, State of": "PS",
            "Panama": "PA",
            "Papua New Guinea": "PG",
            "Paraguay": "PY",
            "Peru": "PE",
            "Philippines": "PH",
            "Pitcairn": "PN",
            "Poland": "PL",
            "Portugal": "PT",
            "Puerto Rico": "PR",
            "Qatar": "QA",
            "Réunion": "RE",
            "Romania": "RO",
            "Russian Federation": "RU",
            "Rwanda": "RW",
            "Saint Barthélemy": "BL",
            "Saint Helena, Ascension and Tristan da Cunha": "SH",
            "Saint Kitts and Nevis": "KN",
            "Saint Lucia": "LC",
            "Saint Martin (French part)": "MF",
            "Saint Pierre and Miquelon": "PM",
            "Saint Vincent and the Grenadines": "VC",
            "Samoa": "WS",
            "San Marino": "SM",
            "Sao Tome and Principe": "ST",
            "Saudi Arabia": "SA",
            "Senegal": "SN",
            "Serbia": "RS",
            "Seychelles": "SC",
            "Sierra Leone": "SL",
            "Singapore": "SG",
            "Sint Maarten (Dutch part)": "SX",
            "Slovakia": "SK",
            "Slovenia": "SI",
            "Solomon Islands": "SB",
            "Somalia": "SO",
            "South Africa": "ZA",
            "South Georgia and the South Sandwich Islands": "GS",
            "South Sudan": "SS",
            "Spain": "ES",
            "Sri Lanka": "LK",
            "Sudan": "SD",
            "Suriname": "SR",
            "Svalbard and Jan Mayen": "SJ",
            "Sweden": "SE",
            "Switzerland": "CH",
            "Syrian Arab Republic": "SY",
            "Taiwan": "TW",
            "Tajikistan": "TJ",
            "Tanzania, United Republic of": "TZ",
            "Thailand": "TH",
            "Timor-Leste": "TL",
            "Togo": "TG",
            "Tokelau": "TK",
            "Tonga": "TO",
            "Trinidad and Tobago": "TT",
            "Tunisia": "TN",
            "Turkey": "TR",
            "Turkmenistan": "TM",
            "Turks and Caicos Islands": "TC",
            "Tuvalu": "TV",
            "Uganda": "UG",
            "Ukraine": "UA",
            "United Arab Emirates": "AE",
            "United Kingdom of Great Britain and Northern Ireland": "GB",
            "United States of America": "US",
            "United States Minor Outlying Islands": "UM",
            "Uruguay": "UY",
            "Uzbekistan": "UZ",
            "Vanuatu": "VU",
            "Venezuela (Bolivarian Republic of)": "VE",
            "Viet Nam": "VN",
            "Virgin Islands (British)": "VG",
            "Virgin Islands (U.S.)": "VI",
            "Wallis and Futuna": "WF",
            "Western Sahara": "EH",
            "Yemen": "YE",
            "Zambia": "ZM",
            "Zimbabwe": "ZW",
            }
        self.comboBox.clear()
        self.comboBox.addItems(sorted(dic_of_countries.keys()))
        self.label_5.setText(_translate("MainWindow", "Name of Valuer"))
        self.label_6.setText(_translate("MainWindow", "Job Number"))
        self.label_7.setText(_translate("MainWindow", "Client"))
        self.label_8.setText(_translate("MainWindow", "Country"))
        self.label_9.setText(_translate("MainWindow", "Base Year"))
        self.pushButton_2.setText(_translate("MainWindow", "Input Parameters"))
        self.pushButton_4.setText(_translate("MainWindow", "Structure Works Data"))
        self.pushButton_3.setText(_translate("MainWindow", "Foundation"))
        self.pushButton_12.setText(_translate("MainWindow", "Super-Structure"))
        self.pushButton_11.setText(_translate("MainWindow", "Sub-Structure"))
        self.pushButton_13.setText(_translate("MainWindow", "Miscellaneous"))
        self.pushButton_6.setText(_translate("MainWindow", "Financial Data"))
        self.pushButton_5.setText(_translate("MainWindow", "Carbon Emission Data"))
        self.pushButton_14.setText(_translate("MainWindow", "Carbon Emission Cost Data"))
        self.pushButton_7.setText(_translate("MainWindow", "Bridge and Traffic Data"))
        self.pushButton_8.setText(_translate("MainWindow", "Maintenance and Repair"))
        self.pushButton_9.setText(_translate("MainWindow", "Disposal and Recycling"))
        self.pushButton_10.setText(_translate("MainWindow", "Outputs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Project Details"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Results"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Compare"))
        self.label.setText(_translate("MainWindow", "Windows:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionCreate_a_Copy.setText(_translate("MainWindow", "Create a Copy"))
        self.actionPrint.setText(_translate("MainWindow", "Print"))
        self.actionRename.setText(_translate("MainWindow", "Rename"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
        self.actionVersion_History.setText(_translate("MainWindow", "Version History"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionContact_Us.setText(_translate("MainWindow", "Contact Us"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))
        self.actionVideo_Tutorials.setText(_translate("MainWindow", "Video Tutorials"))
        self.actionJoin_our_Community.setText(_translate("MainWindow", "Join our Community"))
        self.actionEdit.setText(_translate("MainWindow", "Edit"))
        self.actionFile.setText(_translate("MainWindow", "File"))
        self.actionOpen_File.setText(_translate("MainWindow", "Open File"))

    def show_outputs_section(self, checked):
        # For now, Outputs button click doesn't show anything specific
        # You can implement showing another widget if needed
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
